"""Checking if admin will work.

Revision ID: 222d7ad7678f
Revises: 27133bcb7023
Create Date: 2025-01-19 18:45:55.792384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222d7ad7678f'
down_revision = '27133bcb7023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
