"""Test.

Revision ID: 27133bcb7023
Revises: d56cdcc021aa
Create Date: 2025-01-19 18:42:05.909875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27133bcb7023'
down_revision = 'd56cdcc021aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
